name: Build and deploy to crates.io

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Install nightly toolchain
        run: rustup toolchain install nightly

      - name: Add rust fmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check

      - name: Deploy to crates.io
        run: cargo publish --token {{ secrets.CARGO_REGISTRY_TOKEN }}
